# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_to_grab.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.name = QtWidgets.QCheckBox(self.centralwidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 9, 0, 1, 1)
        self.bnPlayers = QtWidgets.QCheckBox(self.centralwidget)
        self.bnPlayers.setObjectName("bnPlayers")
        self.gridLayout.addWidget(self.bnPlayers, 10, 0, 1, 1)
        self.nRatings = QtWidgets.QCheckBox(self.centralwidget)
        self.nRatings.setObjectName("nRatings")
        self.gridLayout.addWidget(self.nRatings, 14, 0, 1, 1)
        self.bgg_rank = QtWidgets.QCheckBox(self.centralwidget)
        self.bgg_rank.setObjectName("bgg_rank")
        self.gridLayout.addWidget(self.bgg_rank, 15, 0, 1, 1)
        self.integrations = QtWidgets.QCheckBox(self.centralwidget)
        self.integrations.setObjectName("integrations")
        self.gridLayout.addWidget(self.integrations, 6, 0, 1, 1)
        self.designers = QtWidgets.QCheckBox(self.centralwidget)
        self.designers.setObjectName("designers")
        self.gridLayout.addWidget(self.designers, 2, 0, 1, 1)
        self.nPlayers = QtWidgets.QCheckBox(self.centralwidget)
        self.nPlayers.setObjectName("nPlayers")
        self.gridLayout.addWidget(self.nPlayers, 12, 0, 1, 1)
        self.expans = QtWidgets.QCheckBox(self.centralwidget)
        self.expans.setObjectName("expans")
        self.gridLayout.addWidget(self.expans, 18, 0, 1, 1)
        self.categories = QtWidgets.QCheckBox(self.centralwidget)
        self.categories.setObjectName("categories")
        self.gridLayout.addWidget(self.categories, 7, 0, 1, 1)
        self.age = QtWidgets.QCheckBox(self.centralwidget)
        self.age.setObjectName("age")
        self.gridLayout.addWidget(self.age, 16, 0, 1, 1)
        self.type = QtWidgets.QCheckBox(self.centralwidget)
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 0, 0, 1, 1)
        self.nExpan = QtWidgets.QCheckBox(self.centralwidget)
        self.nExpan.setObjectName("nExpan")
        self.gridLayout.addWidget(self.nExpan, 17, 0, 1, 1)
        self.complexity = QtWidgets.QCheckBox(self.centralwidget)
        self.complexity.setObjectName("complexity")
        self.gridLayout.addWidget(self.complexity, 3, 0, 1, 1)
        self.mechanisms = QtWidgets.QCheckBox(self.centralwidget)
        self.mechanisms.setObjectName("mechanisms")
        self.gridLayout.addWidget(self.mechanisms, 4, 0, 1, 1)
        self.year = QtWidgets.QCheckBox(self.centralwidget)
        self.year.setObjectName("year")
        self.gridLayout.addWidget(self.year, 11, 0, 1, 1)
        self.gb_analysis = QtWidgets.QCheckBox(self.centralwidget)
        self.gb_analysis.setObjectName("gb_analysis")
        self.gridLayout.addWidget(self.gb_analysis, 8, 0, 1, 1)
        self.playTime = QtWidgets.QCheckBox(self.centralwidget)
        self.playTime.setObjectName("playTime")
        self.gridLayout.addWidget(self.playTime, 13, 0, 1, 1)
        self.publisher = QtWidgets.QCheckBox(self.centralwidget)
        self.publisher.setObjectName("publisher")
        self.gridLayout.addWidget(self.publisher, 5, 0, 1, 1)
        self.artists = QtWidgets.QCheckBox(self.centralwidget)
        self.artists.setObjectName("artists")
        self.gridLayout.addWidget(self.artists, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.bnPlayers.setText(_translate("MainWindow", "Best Number of Players"))
        self.nRatings.setText(_translate("MainWindow", "Number of Ratings"))
        self.bgg_rank.setText(_translate("MainWindow", "BGG Rank"))
        self.integrations.setText(_translate("MainWindow", "Integrations"))
        self.designers.setText(_translate("MainWindow", "Designers"))
        self.nPlayers.setText(_translate("MainWindow", "Number of Players"))
        self.expans.setText(_translate("MainWindow", "Expansion Names"))
        self.categories.setText(_translate("MainWindow", "Categories"))
        self.age.setText(_translate("MainWindow", "Age"))
        self.type.setText(_translate("MainWindow", "Type"))
        self.nExpan.setText(_translate("MainWindow", "Number of Expansions"))
        self.complexity.setText(_translate("MainWindow", "Complexity"))
        self.mechanisms.setText(_translate("MainWindow", "Mechanisms"))
        self.year.setText(_translate("MainWindow", "Year"))
        self.gb_analysis.setText(_translate("MainWindow", "Geek Buddy Analysis"))
        self.playTime.setText(_translate("MainWindow", "Playtime"))
        self.publisher.setText(_translate("MainWindow", "Publishers"))
        self.artists.setText(_translate("MainWindow", "Artists"))
