# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_to_grab.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 386)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.age = QtWidgets.QCheckBox(self.centralwidget)
        self.age.setChecked(False)
        self.age.setObjectName("age")
        self.gridLayout_2.addWidget(self.age, 2, 0, 1, 1)
        self.playTime = QtWidgets.QCheckBox(self.centralwidget)
        self.playTime.setChecked(False)
        self.playTime.setObjectName("playTime")
        self.gridLayout_2.addWidget(self.playTime, 2, 1, 1, 1)
        self.nPlayers = QtWidgets.QCheckBox(self.centralwidget)
        self.nPlayers.setChecked(False)
        self.nPlayers.setObjectName("nPlayers")
        self.gridLayout_2.addWidget(self.nPlayers, 3, 0, 1, 1)
        self.description = QtWidgets.QCheckBox(self.centralwidget)
        self.description.setObjectName("description")
        self.gridLayout_2.addWidget(self.description, 4, 0, 1, 1)
        self.image = QtWidgets.QCheckBox(self.centralwidget)
        self.image.setObjectName("image")
        self.gridLayout_2.addWidget(self.image, 4, 1, 1, 1)
        self.name = QtWidgets.QCheckBox(self.centralwidget)
        self.name.setEnabled(False)
        self.name.setCheckable(True)
        self.name.setChecked(True)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 1, 0, 1, 1)
        self.year = QtWidgets.QCheckBox(self.centralwidget)
        self.year.setChecked(False)
        self.year.setObjectName("year")
        self.gridLayout_2.addWidget(self.year, 3, 1, 1, 1)
        self.bggUID = QtWidgets.QCheckBox(self.centralwidget)
        self.bggUID.setEnabled(False)
        self.bggUID.setChecked(True)
        self.bggUID.setObjectName("bggUID")
        self.gridLayout_2.addWidget(self.bggUID, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout.setStretch(1, 15)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 2, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.grabButton = QtWidgets.QPushButton(self.centralwidget)
        self.grabButton.setObjectName("grabButton")
        self.gridLayout_5.addWidget(self.grabButton, 0, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_5.addWidget(self.cancelButton, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 3, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.bnPlayers = QtWidgets.QCheckBox(self.centralwidget)
        self.bnPlayers.setObjectName("bnPlayers")
        self.gridLayout_4.addWidget(self.bnPlayers, 0, 0, 1, 1)
        self.bgg_rank = QtWidgets.QCheckBox(self.centralwidget)
        self.bgg_rank.setChecked(False)
        self.bgg_rank.setObjectName("bgg_rank")
        self.gridLayout_4.addWidget(self.bgg_rank, 1, 0, 1, 1)
        self.complexity = QtWidgets.QCheckBox(self.centralwidget)
        self.complexity.setChecked(False)
        self.complexity.setObjectName("complexity")
        self.gridLayout_4.addWidget(self.complexity, 2, 0, 1, 1)
        self.nRatings = QtWidgets.QCheckBox(self.centralwidget)
        self.nRatings.setObjectName("nRatings")
        self.gridLayout_4.addWidget(self.nRatings, 1, 1, 1, 1)
        self.rating = QtWidgets.QCheckBox(self.centralwidget)
        self.rating.setObjectName("rating")
        self.gridLayout_4.addWidget(self.rating, 0, 1, 1, 1)
        self.bgg_link = QtWidgets.QCheckBox(self.centralwidget)
        self.bgg_link.setObjectName("bgg_link")
        self.gridLayout_4.addWidget(self.bgg_link, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.verticalLayout_3.setStretch(1, 15)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mechanisms = QtWidgets.QCheckBox(self.centralwidget)
        self.mechanisms.setChecked(False)
        self.mechanisms.setObjectName("mechanisms")
        self.gridLayout_3.addWidget(self.mechanisms, 2, 0, 1, 1)
        self.nExpan = QtWidgets.QCheckBox(self.centralwidget)
        self.nExpan.setChecked(False)
        self.nExpan.setObjectName("nExpan")
        self.gridLayout_3.addWidget(self.nExpan, 2, 1, 1, 1)
        self.expans = QtWidgets.QCheckBox(self.centralwidget)
        self.expans.setObjectName("expans")
        self.gridLayout_3.addWidget(self.expans, 1, 1, 1, 1)
        self.designers = QtWidgets.QCheckBox(self.centralwidget)
        self.designers.setObjectName("designers")
        self.gridLayout_3.addWidget(self.designers, 1, 0, 1, 1)
        self.categories = QtWidgets.QCheckBox(self.centralwidget)
        self.categories.setChecked(False)
        self.categories.setObjectName("categories")
        self.gridLayout_3.addWidget(self.categories, 0, 1, 1, 1)
        self.artists = QtWidgets.QCheckBox(self.centralwidget)
        self.artists.setObjectName("artists")
        self.gridLayout_3.addWidget(self.artists, 0, 0, 1, 1)
        self.publisher = QtWidgets.QCheckBox(self.centralwidget)
        self.publisher.setObjectName("publisher")
        self.gridLayout_3.addWidget(self.publisher, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_2.setStretch(1, 15)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 2, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Select Data to Grab"))
        self.label.setText(_translate("MainWindow", "Basic Info"))
        self.age.setText(_translate("MainWindow", "Age"))
        self.playTime.setText(_translate("MainWindow", "Playtime"))
        self.nPlayers.setText(_translate("MainWindow", "Number of Players"))
        self.description.setText(_translate("MainWindow", "Description"))
        self.image.setText(_translate("MainWindow", "Image"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.year.setText(_translate("MainWindow", "Year"))
        self.bggUID.setText(_translate("MainWindow", "BGG ID"))
        self.grabButton.setText(_translate("MainWindow", "Grab"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.label_3.setText(_translate("MainWindow", "Board Game Geek Info"))
        self.bnPlayers.setText(_translate("MainWindow", "Best Number of Players"))
        self.bgg_rank.setText(_translate("MainWindow", "BGG Rank"))
        self.complexity.setText(_translate("MainWindow", "Complexity"))
        self.nRatings.setText(_translate("MainWindow", "Number of Ratings"))
        self.rating.setText(_translate("MainWindow", "Rating"))
        self.bgg_link.setText(_translate("MainWindow", "BGG Link"))
        self.label_2.setText(_translate("MainWindow", "Extra Info"))
        self.mechanisms.setText(_translate("MainWindow", "Mechanisms"))
        self.nExpan.setText(_translate("MainWindow", "Number of Expansions"))
        self.expans.setText(_translate("MainWindow", "Expansion Names"))
        self.designers.setText(_translate("MainWindow", "Designers"))
        self.categories.setText(_translate("MainWindow", "Categories"))
        self.artists.setText(_translate("MainWindow", "Artists"))
        self.publisher.setText(_translate("MainWindow", "Publishers"))
        self.label_4.setText(_translate("MainWindow", "Information to Grab:"))
